//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateWorker.VMTServiceForCuttingTool {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.ve.me.imis.ncku", ConfigurationName="VMTServiceForCuttingTool.VMTServicePortType")]
    public interface VMTServicePortType {
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="urn:VMTServiceForCuttingTool", ReplyAction="urn:VMTServiceForCuttingToolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PrivateWorker.VMTServiceForCuttingTool.VMTServiceForCuttingToolResponse VMTServiceForCuttingTool(PrivateWorker.VMTServiceForCuttingTool.VMTServiceForCuttingToolRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VMTServiceForCuttingTool", WrapperNamespace="http://service.ve.me.imis.ncku", IsWrapped=true)]
    public partial class VMTServiceForCuttingToolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.ve.me.imis.ncku", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NCFilePathList;
        
        public VMTServiceForCuttingToolRequest() {
        }
        
        public VMTServiceForCuttingToolRequest(string NCFilePathList) {
            this.NCFilePathList = NCFilePathList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VMTServiceForCuttingToolResponse", WrapperNamespace="http://service.ve.me.imis.ncku", IsWrapped=true)]
    public partial class VMTServiceForCuttingToolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.ve.me.imis.ncku", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public VMTServiceForCuttingToolResponse() {
        }
        
        public VMTServiceForCuttingToolResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VMTServicePortTypeChannel : PrivateWorker.VMTServiceForCuttingTool.VMTServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VMTServicePortTypeClient : System.ServiceModel.ClientBase<PrivateWorker.VMTServiceForCuttingTool.VMTServicePortType>, PrivateWorker.VMTServiceForCuttingTool.VMTServicePortType {
        
        public VMTServicePortTypeClient() {
        }
        
        public VMTServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VMTServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VMTServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VMTServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateWorker.VMTServiceForCuttingTool.VMTServiceForCuttingToolResponse PrivateWorker.VMTServiceForCuttingTool.VMTServicePortType.VMTServiceForCuttingTool(PrivateWorker.VMTServiceForCuttingTool.VMTServiceForCuttingToolRequest request) {
            return base.Channel.VMTServiceForCuttingTool(request);
        }
        
        public string VMTServiceForCuttingTool(string NCFilePathList) {
            PrivateWorker.VMTServiceForCuttingTool.VMTServiceForCuttingToolRequest inValue = new PrivateWorker.VMTServiceForCuttingTool.VMTServiceForCuttingToolRequest();
            inValue.NCFilePathList = NCFilePathList;
            PrivateWorker.VMTServiceForCuttingTool.VMTServiceForCuttingToolResponse retVal = ((PrivateWorker.VMTServiceForCuttingTool.VMTServicePortType)(this)).VMTServiceForCuttingTool(inValue);
            return retVal.@return;
        }
    }
}
