//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateWorker.TimeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://time.mmdb.imis", ConfigurationName="TimeService.DataTimePortType")]
    public interface DataTimePortType {
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="urn:TimeDisplay", ReplyAction="urn:TimeDisplayResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PrivateWorker.TimeService.TimeDisplayResponse TimeDisplay(PrivateWorker.TimeService.TimeDisplayRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="urn:DateTimeDisplay", ReplyAction="urn:DateTimeDisplayResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PrivateWorker.TimeService.DateTimeDisplayResponse DateTimeDisplay(PrivateWorker.TimeService.DateTimeDisplayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimeDisplay", WrapperNamespace="http://time.mmdb.imis", IsWrapped=true)]
    public partial class TimeDisplayRequest {
        
        public TimeDisplayRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimeDisplayResponse", WrapperNamespace="http://time.mmdb.imis", IsWrapped=true)]
    public partial class TimeDisplayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://time.mmdb.imis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public TimeDisplayResponse() {
        }
        
        public TimeDisplayResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DateTimeDisplay", WrapperNamespace="http://time.mmdb.imis", IsWrapped=true)]
    public partial class DateTimeDisplayRequest {
        
        public DateTimeDisplayRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DateTimeDisplayResponse", WrapperNamespace="http://time.mmdb.imis", IsWrapped=true)]
    public partial class DateTimeDisplayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://time.mmdb.imis", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public DateTimeDisplayResponse() {
        }
        
        public DateTimeDisplayResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataTimePortTypeChannel : PrivateWorker.TimeService.DataTimePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataTimePortTypeClient : System.ServiceModel.ClientBase<PrivateWorker.TimeService.DataTimePortType>, PrivateWorker.TimeService.DataTimePortType {
        
        public DataTimePortTypeClient() {
        }
        
        public DataTimePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataTimePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTimePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTimePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateWorker.TimeService.TimeDisplayResponse PrivateWorker.TimeService.DataTimePortType.TimeDisplay(PrivateWorker.TimeService.TimeDisplayRequest request) {
            return base.Channel.TimeDisplay(request);
        }
        
        public string TimeDisplay() {
            PrivateWorker.TimeService.TimeDisplayRequest inValue = new PrivateWorker.TimeService.TimeDisplayRequest();
            PrivateWorker.TimeService.TimeDisplayResponse retVal = ((PrivateWorker.TimeService.DataTimePortType)(this)).TimeDisplay(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateWorker.TimeService.DateTimeDisplayResponse PrivateWorker.TimeService.DataTimePortType.DateTimeDisplay(PrivateWorker.TimeService.DateTimeDisplayRequest request) {
            return base.Channel.DateTimeDisplay(request);
        }
        
        public string DateTimeDisplay() {
            PrivateWorker.TimeService.DateTimeDisplayRequest inValue = new PrivateWorker.TimeService.DateTimeDisplayRequest();
            PrivateWorker.TimeService.DateTimeDisplayResponse retVal = ((PrivateWorker.TimeService.DataTimePortType)(this)).DateTimeDisplay(inValue);
            return retVal.@return;
        }
    }
}
